import { ImageResponse } from "next/og";
import { parseAddress } from "@/lib/address";
import { resolveChain } from "@/lib/chains";
import { decodeHookAddress } from "@/lib/decode";
import { PERMISSIONS } from "@/lib/flags";

export const runtime = "edge";

export const OG_SIZE = { width: 1200, height: 630 };
export const OG_ALT = "Uniswap v4 hook permissions decoded from the contract address";

const INK_950 = "#0a0a0f";
const INK_800 = "#1c1c27";
const INK_700 = "#2a2a38";
const INK_600 = "#3d3d4e";
const INK_400 = "#7a7a92";
const INK_100 = "#e6e6ef";
const PINK = "#ff007a";
const PINK_SOFT = "#ff4d9e";

/**
 * Dynamic Open Graph card.
 *
 * A route handler rather than the `opengraph-image.tsx` convention on purpose: that
 * convention only receives route segment `params`, never `searchParams`, so it cannot
 * see `?address=`. Since this app keeps its whole state in the query string, the image
 * has to be generated by something that can read a query string -- which is this.
 *
 * `next/og` supports only a flexbox subset of CSS, with no external fonts or images,
 * so everything below is inline styles on divs.
 */
export async function GET(request: Request) {
  const params = new URL(request.url).searchParams;
  const parsed = parseAddress(params.get("address") ?? "");

  if (!parsed.ok) {
    return new ImageResponse(<LandingCard />, OG_SIZE);
  }

  const chain = resolveChain(params.get("chain"));
  const decoded = decodeHookAddress(parsed.address);

  return new ImageResponse(
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        background: INK_950,
        padding: 64,
        fontFamily: "monospace",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
        <div
          style={{
            display: "flex",
            background: "rgba(255,0,122,0.15)",
            color: PINK_SOFT,
            padding: "6px 14px",
            borderRadius: 8,
            fontSize: 22,
            fontWeight: 700,
            letterSpacing: 1,
          }}
        >
          UNISWAP V4
        </div>
        <div style={{ display: "flex", color: INK_400, fontSize: 24 }}>{chain.label}</div>
      </div>

      {/* The address, with the permission-carrying suffix highlighted. */}
      <div style={{ display: "flex", marginTop: 32, fontSize: 32 }}>
        <span style={{ color: INK_100 }}>{parsed.address.slice(0, -4)}</span>
        <span
          style={{
            color: PINK_SOFT,
            background: "rgba(255,0,122,0.18)",
            padding: "0 6px",
            borderRadius: 6,
          }}
        >
          {parsed.address.slice(-4)}
        </span>
      </div>

      <div style={{ display: "flex", marginTop: 12, fontSize: 22, color: INK_400 }}>
        {decoded.activeCount} of 14 permissions active · mask {decoded.maskedHex}
      </div>

      {/* All 14 permissions, lit if the bit is set. */}
      <div style={{ display: "flex", flexWrap: "wrap", gap: 9, marginTop: 30, maxWidth: 1072 }}>
        {PERMISSIONS.map((p) => {
          const active = decoded.permissions[p.key];
          return (
            <div
              key={p.key}
              style={{
                display: "flex",
                alignItems: "center",
                gap: 8,
                padding: "9px 13px",
                borderRadius: 10,
                border: `1px solid ${active ? PINK : INK_700}`,
                background: active ? "rgba(255,0,122,0.12)" : INK_800,
                color: active ? INK_100 : INK_600,
                fontSize: 18,
              }}
            >
              <div
                style={{
                  display: "flex",
                  width: 8,
                  height: 8,
                  borderRadius: 4,
                  background: active ? PINK : INK_600,
                }}
              />
              {p.label}
            </div>
          );
        })}
      </div>

      <div style={{ display: "flex", flex: 1 }} />
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          borderTop: `1px solid ${INK_700}`,
          paddingTop: 20,
          fontSize: 20,
          color: INK_400,
        }}
      >
        <div style={{ display: "flex", color: INK_100, fontWeight: 700 }}>Hook Explorer</div>
        <div style={{ display: "flex" }}>Permissions are encoded in the address</div>
      </div>
    </div>,
    OG_SIZE,
  );
}

function LandingCard() {
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        background: INK_950,
        padding: 80,
        fontFamily: "monospace",
      }}
    >
      <div
        style={{
          display: "flex",
          background: "rgba(255,0,122,0.15)",
          color: PINK_SOFT,
          padding: "8px 18px",
          borderRadius: 10,
          fontSize: 26,
          fontWeight: 700,
          letterSpacing: 1,
          alignSelf: "flex-start",
        }}
      >
        UNISWAP V4
      </div>
      <div
        style={{ display: "flex", fontSize: 84, fontWeight: 700, color: INK_100, marginTop: 28 }}
      >
        Hook Explorer
      </div>
      <div style={{ display: "flex", fontSize: 30, color: INK_400, marginTop: 22, maxWidth: 900 }}>
        Decode a v4 hook&apos;s permissions straight from its address, plus risk heuristics and the
        pools that use it.
      </div>
    </div>
  );
}
